version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: vacancy_scanner_mysql
    environment:
      MYSQL_DATABASE: vacancyscanner
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network: